"""empty message

Revision ID: 4dec8b019cad
Revises: 8d9f1e9f106d
Create Date: 2020-06-23 13:32:44.040007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dec8b019cad'
down_revision = '8d9f1e9f106d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=True),
    sa.Column('Email', sa.String(length=50), nullable=True),
    sa.Column('Password', sa.String(length=50), nullable=True),
    sa.Column('ConfirmPassword', sa.String(length=50), nullable=True),
    sa.Column('Contact', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
