"""empty message

Revision ID: 9aec7a78ea7e
Revises: 858d69ea7ea9
Create Date: 2020-07-07 12:52:48.554456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aec7a78ea7e'
down_revision = '858d69ea7ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('priority', sa.String(length=5), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tasks')
    # ### end Alembic commands ###
